export const OMNIUTIL_CONTEXT = {
  CONTRACT_ADDRESS: "0xcFFDa93651Fc8a514e3B06A7a7bA4BEe663B8bA1",
  CHAIN: "BSC",
  MODE: "LIVE",
  UTIL_PAIR: "UTIL/USDT",
  QR_ENTRY: true,
  AI_ACTIVE: true,
  ORCHESTRATOR_ACTIVE: true
};
